//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.3.0
//     from Assets/ControllSchreame/SensorControlls.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @SensorControlls : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @SensorControlls()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""SensorControlls"",
    ""maps"": [
        {
            ""name"": ""Default"",
            ""id"": ""f8ead9df-d3af-429a-8413-c91b7d41a743"",
            ""actions"": [
                {
                    ""name"": ""Gyro"",
                    ""type"": ""Value"",
                    ""id"": ""615bc6e7-b8a0-4683-8448-dbcb8d2330e6"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""f31f1c95-bccb-4b3e-a83a-88d08c68aef8"",
                    ""path"": ""<Gyroscope>/angularVelocity"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Gyro"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": [
        {
            ""name"": ""Mobil"",
            ""bindingGroup"": ""Mobil"",
            ""devices"": [
                {
                    ""devicePath"": ""<Gyroscope>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        }
    ]
}");
        // Default
        m_Default = asset.FindActionMap("Default", throwIfNotFound: true);
        m_Default_Gyro = m_Default.FindAction("Gyro", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Default
    private readonly InputActionMap m_Default;
    private IDefaultActions m_DefaultActionsCallbackInterface;
    private readonly InputAction m_Default_Gyro;
    public struct DefaultActions
    {
        private @SensorControlls m_Wrapper;
        public DefaultActions(@SensorControlls wrapper) { m_Wrapper = wrapper; }
        public InputAction @Gyro => m_Wrapper.m_Default_Gyro;
        public InputActionMap Get() { return m_Wrapper.m_Default; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(DefaultActions set) { return set.Get(); }
        public void SetCallbacks(IDefaultActions instance)
        {
            if (m_Wrapper.m_DefaultActionsCallbackInterface != null)
            {
                @Gyro.started -= m_Wrapper.m_DefaultActionsCallbackInterface.OnGyro;
                @Gyro.performed -= m_Wrapper.m_DefaultActionsCallbackInterface.OnGyro;
                @Gyro.canceled -= m_Wrapper.m_DefaultActionsCallbackInterface.OnGyro;
            }
            m_Wrapper.m_DefaultActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Gyro.started += instance.OnGyro;
                @Gyro.performed += instance.OnGyro;
                @Gyro.canceled += instance.OnGyro;
            }
        }
    }
    public DefaultActions @Default => new DefaultActions(this);
    private int m_MobilSchemeIndex = -1;
    public InputControlScheme MobilScheme
    {
        get
        {
            if (m_MobilSchemeIndex == -1) m_MobilSchemeIndex = asset.FindControlSchemeIndex("Mobil");
            return asset.controlSchemes[m_MobilSchemeIndex];
        }
    }
    public interface IDefaultActions
    {
        void OnGyro(InputAction.CallbackContext context);
    }
}
